### ISSUE TITLE
How I can define custom path for data?

### ISSUE THREAD

**Issue by dmitrirussu** [haseebnqureshi/nosqldb#3]
Hi I need to define a custom path for data, I didnot see that as option, how can I do that ?

**Comment by dmitrirussu** [comment]
I found that process.env.PWD
could be that done as option of nosqldb ?

**Comment by haseebnqureshi** [comment]
Hey @dmitrirussu, sorry about the late reply here! Yeah, absolutely -- you can define process.env.PWD and override the __dirname default.
